"""
query_planner.py — Uses Gemini Flash to convert a natural language query into
a structured SearchPlan dataclass.

The planner is given the full database schema so it knows exactly what columns
exist and can generate precise, executable filter plans.
"""

import json
import re
from dataclasses import dataclass, field
from typing import Optional
from google import genai
from google.genai import types as gtypes

from config import settings
from logger import logger


@dataclass
class SearchPlan:
    """
    Structured search plan generated by the LLM from the user's natural language query.
    This drives both the SQL query and the ChromaDB semantic search.
    """
    # ── Query classification ──────────────────────────────────────────────────
    query_type: str = "SEARCH"
    # SEARCH   — find matching properties  (most common)
    # AGGREGATE — count/summarize ("how many 3 BHK villas are there?")
    # COMPARE  — compare 2+ specific projects by name
    # DETAIL   — deep-dive on one specific project ("full details of KP Villas")

    # ── Hard SQL filters ──────────────────────────────────────────────────────
    cities: list = field(default_factory=list)          # multi-city: ["Ahmedabad","Surat"]
    bhk: Optional[int] = None
    min_bhk: Optional[int] = None                        # for "3 BHK or larger" → bhk >= min_bhk
    property_type: Optional[str] = None                  # APARTMENT/VILLA/ROW_HOUSE/TENEMENT
    min_area_sqft: Optional[float] = None
    max_area_sqft: Optional[float] = None
    entrance_facing: Optional[str] = None                # East/West/North/South

    # ── Unit feature flags (map to has_* columns on units table) ─────────────
    must_have: list = field(default_factory=list)
    # Any of: has_pooja_room, has_study_room, has_terrace, has_servant_room,
    #         has_garden, has_home_theatre, has_gym, has_dressing_room,
    #         has_store_room, has_courtyard, has_balcony

    # ── Project feature flags (map to has_* columns on projects table) ────────
    project_must_have: list = field(default_factory=list)
    # Any of: has_clubhouse, has_pool, has_park, has_sports_courts, has_parking

    # ── FTS5 text search ──────────────────────────────────────────────────────
    locations: list[str] = field(default_factory=list) # "near Karnavati Club" → ["Karnavati Club"], "in Sarkhej" → ["Sarkhej"]
    amenity_query: Optional[str] = None     # "has jogging track" → FTS on amenities
    project_name_query: Optional[str] = None  # specific project name for DETAIL/COMPARE
    compare_projects: list = field(default_factory=list)  # COMPARE: [\"OUM ORBIT\", \"KP Villas\"]

    # ── Semantic vector search ────────────────────────────────────────────────
    semantic_query: str = ""               # rich English phrase for ChromaDB

    # ── Clarification ─────────────────────────────────────────────────────────
    needs_clarification: bool = False
    clarification_question: str = ""


# ─── System Prompt ────────────────────────────────────────────────────────────

_SCHEMA_CONTEXT = """
DATABASE SCHEMA (SQLite):

Table: projects
  Columns: project_id, project_name, developer_name, city, neighbourhood, address,
           has_clubhouse(0/1), has_pool(0/1), has_park(0/1), has_sports_courts(0/1),
           has_parking(0/1), has_commercial_shops(0/1), project_status, possession_date

Table: units (joined to projects)
  Columns: bhk(integer), property_type(APARTMENT/VILLA/ROW_HOUSE/TENEMENT/PENTHOUSE),
           super_builtup_sqft(real), carpet_area_sqft(real), entrance_facing(text),
           has_pooja_room(0/1), has_study_room(0/1), has_terrace(0/1),
           has_servant_room(0/1), has_garden(0/1), has_home_theatre(0/1),
           has_gym(0/1), has_dressing_room(0/1), has_store_room(0/1),
           has_courtyard(0/1), has_lobby(0/1), has_balcony(0/1),
           total_bedrooms(int), attached_bathrooms(int),
           master_bedroom_sqft(real), drawing_room_sqft(real), kitchen_sqft(real)

FTS5 virtual table: projects_fts
  Columns: project_name, developer_name, city, neighbourhood, landmarks_text, amenities_text

Table: rooms (one row per room, joined to units)
  Columns: name, room_type, length, width, area_sqft, floor_level
"""

_SYSTEM_PROMPT = f"""\
You are a precise real estate query planner. Convert the user's message into a structured JSON search plan.

{_SCHEMA_CONTEXT}

PROPERTY TYPE VOCABULARY (CRITICAL — always apply before setting property_type):
Map the user's words to the EXACT enum value. Use the table below:

  ROW_HOUSE  ← raw house, rawhouse, row house, row-house,
                bungalow, bunglow, banglow, bangalow, kothi, independent house
  VILLA      ← villa, villas, luxury villa, duplex villa, twin villa, farmhouse, villa bungalow
  APARTMENT  ← apartment, flat, flats, unit, studio, studio apartment
  TENEMENT   ← tenement, tenaments, tenements, chawl, chawls, gala, galas, old style flat
  PENTHOUSE  ← penthouse, penthouses, sky villa, sky apartment, rooftop apartment

If NONE of the above specific property words are spoken, set property_type = null.
Generic words like "house", "houses", "home", "homes", or "property" alone MUST map to null.

RULES:
1. query_type:
   - SEARCH: any property search query — including "show me", "find me", "list all", "what options" (MOST COMMON)
   - AGGREGATE: ONLY when user explicitly asks for a COUNT or STATISTIC ("how many", "count", "total number of", "which cities have")
   - COMPARE: user explicitly wants to compare 2+ named projects
   - DETAIL: user wants full details on one specific named project
   IMPORTANT: "list all 3 BHK apartments", "show me villas", "find me row houses" → SEARCH, not AGGREGATE.

2. cities: extract all city names as a list. E.g., "Ahmedabad and Surat" → ["Ahmedabad","Surat"]
   IMPORTANT: Only extract REAL Indian city names (e.g., Ahmedabad, Surat, Rajkot, Vadodara, Gandhinagar).
   Do NOT extract generic words or locality names. "in the city", "my city", "Sun City" → cities=[].
   "Sun City", "Sarkhej", "Bopal", "Vizol" are LOCALITIES, not cities → put them in locations[], not cities[].

3. must_have: list of column names from the units table that must equal 1.
   E.g., "with pooja room" → ["has_pooja_room"]
   "with garden and home theatre" → ["has_garden","has_home_theatre"]

4. project_must_have: list of column names from the projects table that must equal 1.
   E.g., "with pool and clubhouse" → ["has_pool","has_clubhouse"]

5. locations: extract a list of ANY specific neighbourhoods, areas, societies, or landmarks mentioned.
   E.g., "near Karnavati Club" → ["Karnavati Club"]
   "in Sarkhej" → ["Sarkhej"]
   "near Sun City" → ["Sun City"]
   "in Sarkhej and Vizol" → ["Sarkhej", "Vizol"]
   Include ALL common spelling variants as separate entries when ambiguous.
   E.g., "Vizol" or "Vinzol" → locations=["Vizol","Vinzol"]

6. amenity_query: set ONLY if user mentions a specific project amenity not in boolean flags.
   E.g., "with jogging track" → "jogging track"

7. semantic_query: always fill with a clean English phrase describing what the user wants.
   This is used for vector search. Make it descriptive and natural.

8. needs_clarification: ONLY true if the user's message is completely empty or totally random.
   Never ask for clarification on aggregation queries or partial queries.

9. property_type must be exactly one of: APARTMENT, VILLA, ROW_HOUSE, TENEMENT, PENTHOUSE, null
   Refer to the PROPERTY TYPE VOCABULARY table at the top — always use that mapping.

10. min_bhk: if user says "3 BHK or larger", "at least 3 BHK", "3+ BHK", "minimum 3 BHK" → set min_bhk=3, leave bhk=null.
    If exact BHK is specified with no qualifier → set bhk=N, leave min_bhk=null.

11. COMPARE queries: populate compare_projects as a JSON array of EACH project name mentioned.
    E.g., "Compare OUM ORBIT and KP Villas" → compare_projects=["OUM ORBIT", "KP Villas"]
    Also set project_name_query to the first project name as a string.

Return ONLY valid JSON matching this schema (no markdown, no extra text):
{{
  "query_type": "SEARCH",
  "cities": [],
  "bhk": null,
  "min_bhk": null,
  "property_type": null,
  "min_area_sqft": null,
  "max_area_sqft": null,
  "entrance_facing": null,
  "must_have": [],
  "project_must_have": [],
  "locations": [],
  "amenity_query": null,
  "project_name_query": null,
  "compare_projects": [],
  "semantic_query": "",
  "needs_clarification": false,
  "clarification_question": ""
}}
"""


# ─── Gemini Client ────────────────────────────────────────────────────────────

def _get_client() -> genai.Client:
    return genai.Client(api_key=settings.GEMINI_API_KEY)


# Generic words that must NOT be treated as city names
_GENERIC_CITY_WORDS = {
    "city", "the city", "my city", "a city", "this city", "our city",
    "town", "the town", "locality", "area", "location",
}


def _parse_raw_json(raw: str, user_message: str) -> SearchPlan:
    """Parse raw JSON string into a SearchPlan."""
    raw = re.sub(r"^```(?:json)?\s*", "", raw.strip(), flags=re.MULTILINE)
    raw = re.sub(r"\s*```$", "", raw, flags=re.MULTILINE)
    parsed = json.loads(raw)

    # Sanitize cities: strip generic words that are not real city names
    if "cities" in parsed and isinstance(parsed["cities"], list):
        parsed["cities"] = [
            c for c in parsed["cities"]
            if c and c.strip().lower() not in _GENERIC_CITY_WORDS
        ]

    # Sanitize string fields that Groq may incorrectly return as a list
    for field_name in ("project_name_query", "amenity_query", "semantic_query"):
        val = parsed.get(field_name)
        if isinstance(val, list):
            parsed[field_name] = " ".join(str(x) for x in val) if val else None

    # If COMPARE and compare_projects not set, try to auto-extract from project_name_query
    if parsed.get("query_type") == "COMPARE":
        cp = parsed.get("compare_projects", [])
        pnq = parsed.get("project_name_query") or ""
        if not cp and pnq:
            # project_name_query may contain both names separated by space/and
            parsed["compare_projects"] = [pnq]

    valid_fields = SearchPlan.__dataclass_fields__
    filtered = {k: v for k, v in parsed.items() if k in valid_fields}
    plan = SearchPlan(**filtered)
    logger.debug(
        f"SearchPlan: type={plan.query_type} cities={plan.cities} "
        f"bhk={plan.bhk} min_bhk={getattr(plan, 'min_bhk', None)} ptype={plan.property_type} must={plan.must_have}"
    )
    return plan


def plan_query(
    user_message: str,
    conversation_history: list[dict] | None = None,
) -> SearchPlan:
    """
    Call Groq to convert user message to a SearchPlan.

    Args:
        user_message: The latest user input.
        conversation_history: Optional list of previous {role, content} dicts.

    Returns:
        SearchPlan with all extracted filters.
    """
    import time
    from groq import Groq

    if not settings.GROQ_API_KEY:
        logger.error("Groq API key not set. Falling back to simple semantic search.")
        return SearchPlan(semantic_query=user_message)

    try:
        client = Groq(api_key=settings.GROQ_API_KEY)
    except Exception as e:
        logger.error(f"Failed to initialize Groq client: {e}")
        return SearchPlan(semantic_query=user_message)

    history_text = ""
    if conversation_history:
        recent = conversation_history[-6:]
        history_text = "\n".join(f"{m['role'].upper()}: {m['content']}" for m in recent)
        history_text = f"\nPrevious conversation:\n{history_text}\n"

    messages = [
        {"role": "system", "content": _SYSTEM_PROMPT + history_text},
        {"role": "user", "content": f"User message to parse: {user_message}"},
    ]

    last_error = None
    for attempt in range(3):
        try:
            resp = client.chat.completions.create(
                model=settings.GROQ_MODEL,
                messages=messages,
                temperature=0.0,
                max_tokens=512,
                response_format={"type": "json_object"}
            )
            raw = resp.choices[0].message.content
            return _parse_raw_json(raw, user_message)

        except json.JSONDecodeError as e:
            logger.error(f"Invalid JSON from Groq: {e}")
            break

        except Exception as e:
            last_error = e
            err_str = str(e).lower()
            if "429" in err_str or "rate limit" in err_str:
                wait = 2 ** attempt
                logger.warning(f"Groq rate limit (attempt {attempt+1}). Retrying in {wait}s...")
                time.sleep(wait)
            else:
                logger.error(f"Groq query planning failed: {e}")
                break

    # Last resort: pure semantic fallback
    return SearchPlan(
        semantic_query=user_message,
        needs_clarification=False,
    )
